<a href="https://colab.research.google.com/github/yashashwi-s/RLbook/blob/main/Bellman_Equation.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
!pip install matplotlib
!pip install numpy

In [2]:
import numpy as np

In [5]:
#constants

WORLD_SIZE = 5
A_POS = [0,1]
B_POS = [0,3]
A_POS_PRIME = [4,1]
B_POS_PRIME = [2,3]

gamma = 0.9

#left, up, right, down
ACTIONS = [np.array([0,-1]),
           np.array([-1,0]),
           np.array([0,1]),
           np.array([1,0])]

ACTION_PROB = 0.25

In [7]:
def step(state, action):
  reward = None
  next_state = None

  if state == A_POS:
    reward = 10
    next_state = A_POS_PRIME
  elif state ==B_POS:
    reward = 5
    next_state = B_POS_PRIME
  else:
    next_state = (np.array(state)+np.array(action)).tolist()
    x,y = next_state
    if(x<0 or x>=WORLD_SIZE or y<0 or y>=WORLD_SIZE):
      reward = -1.0
      next_state = state
    else:
      reward = 0.0
      next_state = (np.array(state) + np.array(action)).tolist()

  return next_state, reward

In [14]:
def bellman_update(value):
  new_value = np.zeros_like(value)

  for i in range (WORLD_SIZE) :
    for j in range (WORLD_SIZE) :
      value_sum = 0
      for action in ACTIONS:
        #getting next state and reward
        (next_i, next_j), reward = step([i,j], action)

        value_sum += ACTION_PROB * (reward + gamma * value[next_i, next_j])

      new_value[i][j] = value_sum
  return new_value

In [24]:
value_0 = np.zeros((WORLD_SIZE, WORLD_SIZE))
VALUE = np.zeros((10001, WORLD_SIZE, WORLD_SIZE), dtype=float)
VALUE[0] = value_0
for i in range(10000):
  VALUE[i+1] = bellman_update(VALUE[i])

print(VALUE[-1])

#Hence we can say that the values presented in book is correct

[[ 3.30899634  8.78929186  4.42761918  5.32236759  1.49217876]
 [ 1.52158807  2.99231786  2.25013995  1.9075717   0.54740271]
 [ 0.05082249  0.73817059  0.67311326  0.35818621 -0.40314114]
 [-0.9735923  -0.43549543 -0.35488227 -0.58560509 -1.18307508]
 [-1.85770055 -1.34523126 -1.22926726 -1.42291815 -1.97517905]]
